// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.Data;

namespace Rental.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200921142027_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rental.Models.TBL_USER", b =>
                {
                    b.Property<int>("A_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("A_ID");

                    b.ToTable("TBL_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
